name: 报告一个BUG
description: 如果你在使用本项目时遇到了问题，请使用这个模板来提交一个BUG报告。
title: "[BUG]: "
labels: ["bug"]
body:
  - type: input
    id: email
    attributes:
      label: 联系方式
      description: 如果您愿意，您可以提供您的邮件地址，以便我们能够联系您。
      placeholder: 例如：example@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: BUG描述
      description: 请简要描述您遇到的问题（可附上屏幕截图）。
      placeholder: 例如：当我运行这个命令时，软件崩溃了。
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: 软件版本
      description: 您正在使用本项目的哪个版本？
      options:
        - 1.1.3
        - 1.1.2
        - 1.1.1
        - 1.1.0
        - 1.0.0
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 请详细描述您是如何遇到这个问题的，以便我们能够复现它。
      placeholder: |
        例如：
        1. 打开软件
        2. 点击某个按钮
        3. 出现错误信息
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志信息
      description: 如果您有任何相关的日志信息，请在这里粘贴它们，或者上传到某个网盘并提供链接。
      placeholder: |
        例如：
        Traceback (most recent call last):
          File "main.py", line 10, in <module>
            do_something()
          File "main.py", line 5, in do_something
            raise Exception("Something went wrong")
        Exception: Something went wrong
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 您期望软件的行为是什么？
      placeholder: 例如：我期望软件能够正常运行，不会崩溃。
    validations:
      required: false
